### PR TITLE
Implementation for third connection

### PR DESCRIPTION
**Pull request by louis030195**

### CODE REVIEW

**Comment by louis030195** [comment]
Current state :
https://gist.github.com/louis030195/c97ee095ffcb7c53275cb56300948ac5

**Comment by rom1504** [comment]
I admit the error is really not clear, but if you read it all, it's saying that MCP_CHARLOGON is not defined for toServer

**Comment by rom1504** [comment]
I fixed it a bit

**Comment by rom1504** [comment]
I think we should rename the client to something that makes sense. For example ClientBnFtp and ClientMcp

**Comment by rom1504** [comment]
step 28

I'm going to merge.

Don't forget to git checkout master then git pull.

**Pull request merged**
